//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuiXachOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int MaAdmin { get; set; }
        public string TenAdmin { get; set; }
        public string DiaChiAdmin { get; set; }
        public Nullable<int> SdtAdmin { get; set; }
        public string EmailAdmin { get; set; }
        public string TenDNAdmin { get; set; }
        public string MatKhauAdmin { get; set; }
    }
}
