//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuiXachOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAP_KHO
    {
        public int STT { get; set; }
        public string TenHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string NhaCungCap { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaNSX { get; set; }
    
        public virtual NHA_SAN_XUAT NHA_SAN_XUAT { get; set; }
        public virtual PHAN_LOAI PHAN_LOAI { get; set; }
    }
}
