//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuiXachOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC
    {
        public int STT { get; set; }
        public string TenTT { get; set; }
        public string TomTat { get; set; }
        public string HinhMinhHoa { get; set; }
        public string href { get; set; }
        public string date { get; set; }
    }
}
